server:
  port: 8002
#eureka
eureka:
  instance:
    hostname: mwkd8002.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://mwkd8000.com:8000/eureka/,http://mwkd8001.com:8001/eureka/