server:
  port: 8080
# 服务名称
spring:
  application:
    name: Gateway
  # 开启 Gateway 服务注册中心服务发现
  cloud:
    gateway:
      routes:
        - id: provider-user-route    # 指定路由的唯一标识
          uri: lb://provider-user # 指定路由服务的地址
          predicates:  # 指定路由的规则
            - Path=/user/**
          filters:
            - StripPrefix=1
      default-filters:
        - name: Hystrix
          args:
            name: fallbackpath
            fallbackUri: forward:/error/failBack
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY,BAD_REQUEST
            methods: GET,POST
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
eureka:
  instance:
    instance-id: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:  http://localhost:8000/eureka/
      #defaultZone: http://mwkd8000.com:8000/eureka/,http://mwkd8001.com:8001/eureka/,http://mwkd8002.com:8002/eureka/