server:
  port: 8001
#eureka
eureka:
  instance:
    hostname: mwkd8001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://mwkd8000.com:8000/eureka/,http://mwkd8002.com:8002/eureka/