server:
  port: 8005
eureka:
  instance:
    prefer-ip-address: true
    instance-id: config
    #ip-address: 172.28.98.12
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:  http://localhost:8000/eureka/
      #defaultZone: http://mwkd8000.com:8000/eureka/,http://mwkd8001.com:8001/eureka/,http://mwkd8002.com:8002/eureka/
